### ISSUE TITLE
problems with `npm install`

### ISSUE THREAD

**Issue by ehehdada** [mintme-com/pool#20]
#### System information

Geth version: a66ba186cc28ba0e5c6d22417f420e504c66ac1f

Redis version: Redis server v=5.0.3 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=afa0decbb6de285f

OS & Version: Linux Debian GNU/Linux 10 \n \l

Commit branch and hash: (`master`, `a66ba186cc28ba0e5c6d22417f420e504c66ac1f`)

#### Expected behaviour

Build front-end

#### Actual behaviour

`npm install` failes:

```
/pool-master/www# npm install

> ember-cli-cookie@0.2.0 postinstall /pool-master/www/node_modules/ember-cli-cookie
> bower install --allow-root

/pool-master/www/node_modules/bower/lib/node_modules/configstore/index.js:54
                                throw err;
                                ^

Error: EACCES: permission denied, open '/root/.config/configstore/bower-github.json'
You don't have access to this file.

    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at Configstore.get (/pool-master/www/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at new Configstore (/pool-master/www/node_modules/bower/lib/node_modules/configstore/index.js:28:45)
    at readCachedConfig (/pool-master/www/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/pool-master/www/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/pool-master/www/node_modules/bower/lib/index.js:16:32)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/root/.config/configstore/bower-github.json'
}
npm WARN babel-plugin-debug-macros@0.2.0 requires a peer of @babel/core@^7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ember-cli-cookie@0.2.0 postinstall: `bower install --allow-root`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-cli-cookie@0.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-10T08_21_16_301Z-debug.log

```

#### Steps to reproduce the behaviour

Follow the commands at the README.md file

**Comment by ehehdada** [comment]
ábout the /root/.npm/_logs/2020-06-10T08_21_16_301Z-debug.log file, it ends with
```
734 silly saveTree | | `-- intl-messageformat@1.3.0
734 silly saveTree | |   `-- intl-messageformat-parser@1.2.0
734 silly saveTree | +-- ember-intl-relativeformat@2.4.2
734 silly saveTree | | `-- intl-relativeformat@1.3.0
734 silly saveTree | +-- exists-sync@0.0.3
734 silly saveTree | +-- formatjs-extract-cldr-data@2.0.0
734 silly saveTree | | +-- cldr-core@28.0.0
734 silly saveTree | | +-- cldr-dates-full@28.0.0
734 silly saveTree | | +-- cldr-numbers-full@28.0.0
734 silly saveTree | | +-- make-plural@2.1.3
734 silly saveTree | | +-- object.assign@4.1.0
734 silly saveTree | | | +-- define-properties@1.1.3
734 silly saveTree | | | | `-- object-keys@1.1.1
734 silly saveTree | | | +-- function-bind@1.1.1
734 silly saveTree | | | +-- has-symbols@1.0.0
734 silly saveTree | | | `-- object-keys@1.1.1
734 silly saveTree | | `-- uglify-js@2.8.29
734 silly saveTree | |   `-- yargs@3.10.0
734 silly saveTree | |     `-- window-size@0.1.0
734 silly saveTree | +-- intl@1.0.1
734 silly saveTree | +-- serialize-javascript@1.7.0
734 silly saveTree | `-- walk-sync@0.2.7
734 silly saveTree +-- ember-load-initializers@0.5.1
734 silly saveTree +-- ember-resolver@2.1.1
734 silly saveTree +-- intl-format-cache@2.0.5
734 silly saveTree `-- loader.js@4.7.0
735 warn babel-plugin-debug-macros@0.2.0 requires a peer of @babel/core@^7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
736 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
737 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
738 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
738 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
738 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
738 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
739 verbose stack Error: ember-cli-cookie@0.2.0 postinstall: `bower install --allow-root`
739 verbose stack Exit status 1
739 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/nodejs/node-v14.4.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
739 verbose stack     at EventEmitter.emit (events.js:315:20)
739 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/nodejs/node-v14.4.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
739 verbose stack     at ChildProcess.emit (events.js:315:20)
739 verbose stack     at maybeClose (internal/child_process.js:1051:16)
739 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
740 verbose pkgid ember-cli-cookie@0.2.0
741 verbose cwd /pool-master/www
742 verbose Linux 4.16.11-100.fc26.x86_64
743 verbose argv "/usr/local/lib/nodejs/node-v14.4.0-linux-x64/bin/node" "/usr/local/lib/nodejs/node-v14.4.0-linux-x64/bin/npm" "install"
744 verbose node v14.4.0
745 verbose npm  v6.14.5
746 error code ELIFECYCLE
747 error errno 1
748 error ember-cli-cookie@0.2.0 postinstall: `bower install --allow-root`
748 error Exit status 1
749 error Failed at the ember-cli-cookie@0.2.0 postinstall script.
749 error This is probably not a problem with npm. There is likely additional logging output above.
750 verbose exit [ 1, true ]

```

**Comment by danielwebimp** [comment]
@ehehdada  you should not run 'npm' as root but as a simple user. 
You should be in the user's directory that you've created to run your pool. 
Follow the guide : https://github.com/mintme-com/pool/wiki/Detailed-guide-about-Webchain-pool-installation . Let me know if you face an issue.

**Comment by ehehdada** [comment]
ah! yeah! thanks for the advise @danielwebimp  I was firstly testing it installing the pool into a docker container, so I didn't create a specific user yet. I'll try with a simple user account.

**Comment by danielwebimp** [comment]
@ehehdada  Ok, please recheck and let me know if everything is now OK on your side.
